package kbaserelationengine.events;

public enum ObjectStatusEventType {
	CREATED,
	NEW_VERSION,
	DELETED,
	SHARED,
	UNSHARED,
	PUBLISHED, //TODO RECON this is generated by the WS reconstructor but is never used otherwise
	PUBLISH_ALL_VERSIONS,
	PUBLISH_ACCESS_GROUP, //TODO NOW need to add access group to access docs public list where access group in groups list
	UNPUBLISHED, //TODO RECON this is generated by the WS reconstructor but is never used otherwise
	UNPUBLISH_ALL_VERSIONS,
	UNPUBLISH_ACCESS_GROUP, //TODO NOW need to remove access group from all access docs public list
	NEW_ALL_VERSIONS,
	RENAME_ALL_VERSIONS,
	DELETE_ALL_VERSIONS,
	UNDELETE_ALL_VERSIONS,
	DELETE_ACCESS_GROUP, //TODO NOW need to remove access group from all access docs
	COPY_ACCESS_GROUP;
}
