# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class KBaseRelationEngine(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def add_workspace_to_index(self, params, context=None):
        """
        This operation means that given workspace will be shared with
        system indexing user with write access. User calling this
        function should be owner of this workspace.
        :param params: instance of type "AddWorkspaceToIndexInput" ->
           structure: parameter "ws_name" of String, parameter "ws_id" of Long
        """
        return self._client.call_method(
            'KBaseRelationEngine.add_workspace_to_index',
            [params], self._service_ver, context)

    def search_types(self, params, context=None):
        """
        :param params: instance of type "SearchTypesInput" -> structure:
           parameter "match_filter" of type "MatchFilter" -> structure:
           parameter "full_text_in_all" of String, parameter
           "access_group_id" of Long, parameter "object_name" of String,
           parameter "parent_guid" of type "GUID" (Global user identificator.
           It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "timestamp" of type "MatchValue" -> structure: parameter
           "value" of String, parameter "int_value" of Long, parameter
           "double_value" of Double, parameter "bool_value" of type "boolean"
           (A boolean. 0 = false, other = true.), parameter "min_int" of
           Long, parameter "max_int" of Long, parameter "min_date" of Long,
           parameter "max_date" of Long, parameter "min_double" of Double,
           parameter "max_double" of Double, parameter "lookupInKeys" of
           mapping from String to type "MatchValue" -> structure: parameter
           "value" of String, parameter "int_value" of Long, parameter
           "double_value" of Double, parameter "bool_value" of type "boolean"
           (A boolean. 0 = false, other = true.), parameter "min_int" of
           Long, parameter "max_int" of Long, parameter "min_date" of Long,
           parameter "max_date" of Long, parameter "min_double" of Double,
           parameter "max_double" of Double, parameter "access_filter" of
           type "AccessFilter" -> structure: parameter "with_private" of type
           "boolean" (A boolean. 0 = false, other = true.), parameter
           "with_public" of type "boolean" (A boolean. 0 = false, other =
           true.), parameter "with_all_history" of type "boolean" (A boolean.
           0 = false, other = true.)
        :returns: instance of type "SearchTypesOutput" -> structure:
           parameter "type_to_count" of mapping from String to Long,
           parameter "search_time" of Long
        """
        return self._client.call_method(
            'KBaseRelationEngine.search_types',
            [params], self._service_ver, context)

    def search_objects(self, params, context=None):
        """
        :param params: instance of type "SearchObjectsInput" -> structure:
           parameter "object_type" of String, parameter "match_filter" of
           type "MatchFilter" -> structure: parameter "full_text_in_all" of
           String, parameter "access_group_id" of Long, parameter
           "object_name" of String, parameter "parent_guid" of type "GUID"
           (Global user identificator. It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "timestamp" of type "MatchValue" -> structure: parameter
           "value" of String, parameter "int_value" of Long, parameter
           "double_value" of Double, parameter "bool_value" of type "boolean"
           (A boolean. 0 = false, other = true.), parameter "min_int" of
           Long, parameter "max_int" of Long, parameter "min_date" of Long,
           parameter "max_date" of Long, parameter "min_double" of Double,
           parameter "max_double" of Double, parameter "lookupInKeys" of
           mapping from String to type "MatchValue" -> structure: parameter
           "value" of String, parameter "int_value" of Long, parameter
           "double_value" of Double, parameter "bool_value" of type "boolean"
           (A boolean. 0 = false, other = true.), parameter "min_int" of
           Long, parameter "max_int" of Long, parameter "min_date" of Long,
           parameter "max_date" of Long, parameter "min_double" of Double,
           parameter "max_double" of Double, parameter "sorting_rules" of
           list of type "SortingRule" -> structure: parameter "is_timestamp"
           of type "boolean" (A boolean. 0 = false, other = true.), parameter
           "is_object_name" of type "boolean" (A boolean. 0 = false, other =
           true.), parameter "key_name" of String, parameter "descending" of
           type "boolean" (A boolean. 0 = false, other = true.), parameter
           "access_filter" of type "AccessFilter" -> structure: parameter
           "with_private" of type "boolean" (A boolean. 0 = false, other =
           true.), parameter "with_public" of type "boolean" (A boolean. 0 =
           false, other = true.), parameter "with_all_history" of type
           "boolean" (A boolean. 0 = false, other = true.), parameter
           "pagination" of type "Pagination" -> structure: parameter "start"
           of Long, parameter "count" of Long, parameter "post_processing" of
           type "PostProcessing" (ids_only - shortcut to mark all three skips
           as true.) -> structure: parameter "ids_only" of type "boolean" (A
           boolean. 0 = false, other = true.), parameter "skip_info" of type
           "boolean" (A boolean. 0 = false, other = true.), parameter
           "skip_keys" of type "boolean" (A boolean. 0 = false, other =
           true.), parameter "skip_data" of type "boolean" (A boolean. 0 =
           false, other = true.), parameter "data_includes" of list of String
        :returns: instance of type "SearchObjectsOutput" -> structure:
           parameter "pagination" of type "Pagination" -> structure:
           parameter "start" of Long, parameter "count" of Long, parameter
           "sorting_rules" of list of type "SortingRule" -> structure:
           parameter "is_timestamp" of type "boolean" (A boolean. 0 = false,
           other = true.), parameter "is_object_name" of type "boolean" (A
           boolean. 0 = false, other = true.), parameter "key_name" of
           String, parameter "descending" of type "boolean" (A boolean. 0 =
           false, other = true.), parameter "objects" of list of type
           "ObjectData" -> structure: parameter "guid" of type "GUID" (Global
           user identificator. It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "parent_guid" of type "GUID" (Global user identificator.
           It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "object_name" of String, parameter "timestamp" of Long,
           parameter "parent_data" of unspecified object, parameter "data" of
           unspecified object, parameter "key_props" of mapping from String
           to String, parameter "total" of Long, parameter "search_time" of
           Long
        """
        return self._client.call_method(
            'KBaseRelationEngine.search_objects',
            [params], self._service_ver, context)

    def get_objects(self, params, context=None):
        """
        :param params: instance of type "GetObjectsInput" -> structure:
           parameter "guids" of list of type "GUID" (Global user
           identificator. It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "post_processing" of type "PostProcessing" (ids_only -
           shortcut to mark all three skips as true.) -> structure: parameter
           "ids_only" of type "boolean" (A boolean. 0 = false, other =
           true.), parameter "skip_info" of type "boolean" (A boolean. 0 =
           false, other = true.), parameter "skip_keys" of type "boolean" (A
           boolean. 0 = false, other = true.), parameter "skip_data" of type
           "boolean" (A boolean. 0 = false, other = true.), parameter
           "data_includes" of list of String
        :returns: instance of type "GetObjectsOutput" -> structure: parameter
           "objects" of list of type "ObjectData" -> structure: parameter
           "guid" of type "GUID" (Global user identificator. It has structure
           like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "parent_guid" of type "GUID" (Global user identificator.
           It has structure like this:
           <data-source-code>:<full-reference>[:<sub-type>/<sub-id>]),
           parameter "object_name" of String, parameter "timestamp" of Long,
           parameter "parent_data" of unspecified object, parameter "data" of
           unspecified object, parameter "key_props" of mapping from String
           to String, parameter "search_time" of Long
        """
        return self._client.call_method(
            'KBaseRelationEngine.get_objects',
            [params], self._service_ver, context)

    def list_types(self, params, context=None):
        """
        :param params: instance of type "ListTypesInput" (type_name -
           optional parameter; if not specified all types are described.) ->
           structure: parameter "type_name" of String
        :returns: instance of type "ListTypesOutput" -> structure: parameter
           "types" of mapping from String to type "TypeDescriptor" (TODO: add
           more details like parent type, relations, primary key, ...) ->
           structure: parameter "type_name" of String, parameter
           "type_ui_title" of String, parameter "keys" of list of type
           "KeyDescription" -> structure: parameter "key_name" of String,
           parameter "key_ui_title" of String, parameter "key_value_type" of
           String
        """
        return self._client.call_method(
            'KBaseRelationEngine.list_types',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('KBaseRelationEngine.status',
                                        [], self._service_ver, context)
